run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic
    - revive
    - exhaustive
    - gosec
    - bodyclose
    - exportloopref
    - sqlclosecheck
    - rowserrcheck

linters-settings:
  govet:
    check-shadowing: true
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/avito-test/pr-reviewer-service
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  revive:
    rules:
      - name: var-naming
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: indent-error-flow
      - name: if-return
      - name: increment-decrement
      - name: range

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
